---
- hosts: all
  become: yes

  vars:
   node_apps_location: /usr/local/opt/node

  tasks:
  - name: Install EPEL repo.
    yum: 
     name: 
     - epel-release
     state: present 
  - name: Import Remi GPG key.
    rpm_key:
      key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
      state: present
    
  - name: Install Remi repo.
    yum:
     name: "https://rpms.remirepo.net/enterprise/8/remi/x86_64/remi-release-8.1-2.el8.remi.noarch.rpm"
     state: present 

  - name: Ensure firewalld is stopped (Since this is for testing).
    service: 
      name: firewalld
      state: stopped
    
  - name: Install Node.js and npm.
    yum:
     name: npm
     state: present
     enablerepo: epel

  - name: Install Forever (This runs Node.js app).
    command: "npm install forever -g"
    
  
  - name: Ensure Node.js app folder Exists.
    file: "path={{ node_apps_location}} state=directory"

  - name: Copy Example Node.js app to server 
    copy: "src=app dest={{ node_apps_location }}"

  - name: Install app dependencies defined in package.json.
    npm: path={{ node_apps_location }}/app

  - name: Check List of Running Node.js apps.
    command: /usr/local/lib/node_modules/forever/bin/forever list
    register: forever_list
    changed_when: false

  - name: Start example Node.js app.
    command: /usr/local/lib/node_modules/forever/bin/forever  start {{ node_apps_location }}/app/app.js
    

    


      
    

  