    #-*-mode:ruby -*-
    #vi:set ft=ruby:

VAGRANTFILE_API_VERSION="2"
Vagrant.configure(VAGRANTFILE_API_VERSION)do|config|

 #General Vagrant VM configuration
 config.vm.box="geerlingguy/centos8"
 config.ssh.insert_key = false
 config.vm.synced_folder ".","/vagrant",disabled:true
 config.vm.provider :virtualbox do|v|
 v.memory =512
 v.linked_clone=true
 end

  #Application server 1.
 config.vm.define"nodeapp"do|app|
 app.vm.hostname= "node-app.test"
 app.vm.network :private_network,ip:"192.168.20.15"
 end

end